package com.thallam.tinyurl.dto;


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.springframework.data.annotation.CreatedDate;

/**
 * UrlEntries generated by hbm2java
 */
@Entity
public class UrlEntries implements java.io.Serializable {

	@Id
	private int urlId;
	private String urlValue;
	private Date createdTime;

	public UrlEntries() {
	}

	public UrlEntries(Date createdTime) {
		this.createdTime = createdTime;
	}

	public UrlEntries(String urlValue, Date createdTime) {
		this.urlValue = urlValue;
		this.createdTime = createdTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "url_id", unique = true, nullable = false)
	public int getUrlId() {
		return this.urlId;
	}

	public void setUrlId(int urlId) {
		this.urlId = urlId;
	}

	@Column(name = "url_value", length = 300)
	public String getUrlValue() {
		return this.urlValue;
	}

	public void setUrlValue(String urlValue) {
		this.urlValue = urlValue;
	}
	
	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
