package com.thallam.tinyurl.dto;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;


/**
 * UrlShortnerMap generated by hbm2java
 */
@Entity
public class UrlShortnerMap implements java.io.Serializable {

	@Id
	private int urlShortId;
	private int urlId;
	private String urlShortValue;
	private Date createdTime;


	public UrlShortnerMap() {
	}

	public UrlShortnerMap(int urlId) {
		this.urlId = urlId;
	}

	public UrlShortnerMap(int urlId, String urlShortValue) {
		this.urlId = urlId;
		this.urlShortValue = urlShortValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "url_short_id", unique = true, nullable = false)
	public int getUrlShortId() {
		return this.urlShortId;
	}

	public void setUrlShortId(int urlShortId) {
		this.urlShortId = urlShortId;
	}

	@Column(name = "url_id", nullable = false)
	public int getUrlId() {
		return this.urlId;
	}

	public void setUrlId(int urlId) {
		this.urlId = urlId;
	}

	@Column(name = "url_short_value", length = 30)
	public String getUrlShortValue() {
		return this.urlShortValue;
	}

	public void setUrlShortValue(String urlShortValue) {
		this.urlShortValue = urlShortValue;
	}
	
	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tiny_url_created_time", length = 30)
	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
